a=input("Ho ten: ")
b=int(input("So ngay cong: "))
c=int(input("Don gia ngay cong: "))
d=float(input("He so phu cap: "))
e=int(input("Tam ung: "))
x=float(c*b*d)
y=float(x-e)
print("Nhan vien",a,end=", ")
print("Co tien Luong=",x,",",sep="",end=" ")
print("Tam ung=",e,sep="",end=" ")
print('va Thuc linh=',y,sep="")